masters:
  hosts:
    master1:
      ansible_host: 10.132.245.21
      ansible_user: k3s 

workers:
  hosts:
    worker1:
      ansible_host: 10.132.245.22
      ansible_user: k3s
    worker2:
      ansible_host: 10.132.245.23
      ansible_user: k3s

all:
  children:
    masters:
    workers:
